version: '3.1'
services:
  gosh:
    build: .
    volumes:
      - .:/code
    ports:
      - "2222:2222"
    expose:
      - "2222"
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    pgdata:
