version: '3.1'
services:
  gosh:
    build: .
    volumes:
      - .:/code
    ports:
      - "2222:2222"
    expose:
      - "2222"
#    depends_on:
#      - redis
#
#  redis:
#    image: redis:alpine
#    volumes:
#      - redisdata:/data

volumes:
    redisdata:
