version: '3.1'
services:
  gosh:
    build: .
    volumes:
      - .:/code
    ports:
      - "2222:2222"
    expose:
      - "2222"
    depends_on:
      - redis
    network_mode: "host"

  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    network_mode: "host"

volumes:
    redisdata:
