version: "3"
services:
  tws:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/work
    environment:
      DISPLAY: ":0"
    ports:
      - "5900:5900"
      - "7497:7497"
